In [2]:
!pip install numpy pandas scikit-learn

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "The product performance is amazing and fast",
    "The service was fast and performance was great",
    "Terrible customer service and bad performance"
]

vectorizer = CountVectorizer(stop_words='english')

X = vectorizer.fit_transform(corpus)

print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("\nBag of Words Matrix:")
print(X.toarray())

Vocabulary:
['amazing' 'bad' 'customer' 'fast' 'great' 'performance' 'product'
 'service' 'terrible']

Bag of Words Matrix:
[[1 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 1 0 1 0]
 [0 1 1 0 0 1 0 1 1]]


In [4]:
df = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)

print(df)

   amazing  bad  customer  fast  great  performance  product  service  \
0        1    0         0     1      0            1        1        0   
1        0    0         0     1      1            1        0        1   
2        0    1         1     0      0            1        0        1   

   terrible  
0         0  
1         0  
2         1  


In [5]:
documents = [
    "Machine learning algorithms analyze structured data effectively.",
    "Deep learning and neural networks excel at processing unstructured data.",
    "Natural language processing helps computers understand human language.",
    "Python is widely used for machine learning and data science."
]

query = ["machine learning algorithms for data"]

print("Documents:")
for i, doc in enumerate(documents, 1):
    print(f"Document {i}: {doc}")

print("\nQuery:")
print(query[0])

Documents:
Document 1: Machine learning algorithms analyze structured data effectively.
Document 2: Deep learning and neural networks excel at processing unstructured data.
Document 3: Natural language processing helps computers understand human language.
Document 4: Python is widely used for machine learning and data science.

Query:
machine learning algorithms for data


In [6]:
vectorizer2 = CountVectorizer(stop_words='english')

doc_vectors = vectorizer2.fit_transform(documents)

print("Document Vectors:")
print(doc_vectors.toarray())

Document Vectors:
[[1 1 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 0 1 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 1 1 2 0 0 1 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 1]]


In [7]:
query_vector = vectorizer2.transform(query)

print("Query Vector:")
print(query_vector.toarray())

Query Vector:
[[1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]]


In [8]:
from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(query_vector, doc_vectors)

print("Similarity Scores:")

for i, score in enumerate(similarities[0], 1):
    print(f"Document {i}: {score:.4f}")

Similarity Scores:
Document 1: 0.7559
Document 2: 0.3536
Document 3: 0.0000
Document 4: 0.5669


In [9]:
best_document = similarities[0].argmax()

print("Most Relevant Document:")
print(documents[best_document])

print("\nHighest Similarity Score:")
print(f"{similarities[0][best_document]:.4f}")

Most Relevant Document:
Machine learning algorithms analyze structured data effectively.

Highest Similarity Score:
0.7559
